apiVersion: apps/v1
kind: Deployment
metadata:
  name: bago-backend
  labels:
    app: bago-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bago-backend
  template:
    metadata:
      labels:
        app: bago-backend
    spec:
      containers:
      - name: bago-backend-container
        image: josanbaq7/bagobackend
        ports:
        - containerPort: 80